[tools]
bat = { version = 'latest' }
bottom = { version = 'latest' }
cheat = { version = 'latest', postinstall = 'mise run postinstall:cheat' }
direnv = { version = 'latest', postinstall = 'mise run postinstall:direnv' }
fd = { version = 'latest' }
fx = { version = 'latest' }
fzf = { version = 'latest', postinstall = 'mise run postinstall:fzf' }
ghq = { version = 'latest' }
github-cli = { version = 'latest', postinstall = 'mise run postinstall:github-cli' }
glow = { version = 'latest', postinstall = 'mise run postinstall:glow' }
jq = { version = 'latest' }
just = { version = 'latest', postinstall = 'mise run postinstall:just' }
lazydocker = { version = 'latest' }
lazygit = { version = 'latest', postinstall = 'mise run postinstall:lazygit' }
neovim = { version = 'latest', postinstall = 'mise run postinstall:neovim' }
nodejs = { version = 'latest', postinstall = 'mise run postinstall:nodejs' }
ripgrep = { version = 'latest', postinstall = 'mise run postinstall:ripgrep' }
shfmt = { version = 'latest' }
tree-sitter = { version = 'latest' } # required by nvim-treesitter
usage = { version = 'latest' }
xh = { version = 'latest', postinstall = 'mise run postinstall:xh' }
yazi = { version = 'latest', postinstall = 'mise run postinstall:yazi' }
